--Relaciones entre tablas
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_USUARIOS_ROLES')
BEGIN
    ALTER TABLE USUARIOS
    ADD CONSTRAINT FK_USUARIOS_ROLES
    FOREIGN KEY (IdRol)
    REFERENCES ROLES(IdRol);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MESAS_RESTAURANTES')
BEGIN
    ALTER TABLE MESAS
    ADD CONSTRAINT FK_MESAS_RESTAURANTES
    FOREIGN KEY (IdRestaurante)
    REFERENCES RESTAURANTES(IdRestaurante);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HORARIOS_USUARIOS')
BEGIN
    ALTER TABLE HORARIOSTRABAJADOR
    ADD CONSTRAINT FK_HORARIOS_USUARIOS
    FOREIGN KEY (IdUsuario)
    REFERENCES USUARIOS(IdUsuario);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PRODUCTOS_CATEGORIAS')
BEGIN
    ALTER TABLE PRODUCTOS
    ADD CONSTRAINT FK_PRODUCTOS_CATEGORIAS
    FOREIGN KEY (IdCategoriaProducto)
    REFERENCES CATEGORIAPRODUCTOS(IdCategoriaProducto);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_INGREDIENTES_PROVEEDORES')
BEGIN
    ALTER TABLE INGREDIENTES
    ADD CONSTRAINT FK_INGREDIENTES_PROVEEDORES
    FOREIGN KEY (IdProveedor)
    REFERENCES PROVEEDORES(IdProveedor);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PRODUCTOINGREDIENTE_PRODUCTOS')
BEGIN
    ALTER TABLE PRODUCTOSINGREDIENTES
    ADD CONSTRAINT FK_PRODUCTOINGREDIENTE_PRODUCTOS
    FOREIGN KEY (IdProducto)
    REFERENCES PRODUCTOS(IdProducto);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PRODUCTOINGREDIENTE_INGREDIENTES')
BEGIN
    ALTER TABLE PRODUCTOSINGREDIENTES
    ADD CONSTRAINT FK_PRODUCTOINGREDIENTE_INGREDIENTES
    FOREIGN KEY (IdIngrediente)
    REFERENCES INGREDIENTES(IdIngrediente);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PEDIDOS_USUARIOS')
BEGIN
    ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDOS_USUARIOS
    FOREIGN KEY (IdUsuario)
    REFERENCES USUARIOS(IdUsuario);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PEDIDOS_MESAS')
BEGIN
    ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDOS_MESAS
    FOREIGN KEY (IdMesa)
    REFERENCES MESAS(IdMesa);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_DETALLEPEDIDOS_PEDIDOS')
BEGIN
    ALTER TABLE DETALLEPEDIDOS
    ADD CONSTRAINT FK_DETALLEPEDIDOS_PEDIDOS
    FOREIGN KEY (IdPedido)
    REFERENCES PEDIDOS(IdPedido)
    ON DELETE CASCADE;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_DETALLEPEDIDOS_PRODUCTOS')
BEGIN
    ALTER TABLE DETALLEPEDIDOS
    ADD CONSTRAINT FK_DETALLEPEDIDOS_PRODUCTOS
    FOREIGN KEY (IdProducto)
    REFERENCES PRODUCTOS(IdProducto);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PEDIDOS_ESTADOS')
BEGIN
    ALTER TABLE PEDIDOS
    ADD CONSTRAINT FK_PEDIDOS_ESTADOS
    FOREIGN KEY (IdEstado)
    REFERENCES ESTADOPEDIDO(IdEstado);
END


GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_RESERVAS_ESTADOS')
BEGIN
    ALTER TABLE RESERVAS
    ADD CONSTRAINT FK_RESERVAS_ESTADOS
    FOREIGN KEY (IdEstado)
    REFERENCES ESTADOSRESERVAS(IdEstado);
END

GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_RESERVAS_USUARIOS')
BEGIN
    ALTER TABLE RESERVAS
    ADD CONSTRAINT FK_RESERVAS_USUARIOS
    FOREIGN KEY (IdUsuario)
    REFERENCES USUARIOS(IdUsuario);
END

GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_RESERVAS_MESAS')
BEGIN
    ALTER TABLE RESERVAS
    ADD CONSTRAINT FK_RESERVAS_MESAS
    FOREIGN KEY (IdMesa)
    REFERENCES MESAS(IdMesa);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PAGOS_PEDIDOS')
BEGIN
    ALTER TABLE PAGOS
    ADD CONSTRAINT FK_PAGOS_PEDIDOS
    FOREIGN KEY (IdPedido)
    REFERENCES PEDIDOS(IdPedido);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PAGOS_METODO')
BEGIN
    ALTER TABLE PAGOS
    ADD CONSTRAINT FK_PAGOS_METODO
    FOREIGN KEY (IdMetodo)
    REFERENCES METODOSPAGOS(IdMetodo);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PAGOS_ESTADO')
BEGIN
    ALTER TABLE PAGOS
    ADD CONSTRAINT FK_PAGOS_ESTADO
    FOREIGN KEY (IdEstado)
    REFERENCES ESTADOPAGO(IdEstado);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_FACTURAS_PAGOS')
BEGIN
    ALTER TABLE FACTURAS
    ADD CONSTRAINT FK_FACTURAS_PAGOS
    FOREIGN KEY (IdPago)
    REFERENCES PAGOS(IdPago);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_FACTURAS_PEDIDOS')
BEGIN
    ALTER TABLE FACTURAS
    ADD CONSTRAINT FK_FACTURAS_PEDIDOS
    FOREIGN KEY (IdPedido)
    REFERENCES PEDIDOS(IdPedido);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_FACTURAS_IMPUESTO')
BEGIN
    ALTER TABLE FACTURAS
    ADD CONSTRAINT FK_FACTURAS_IMPUESTO
    FOREIGN KEY (IdImpuesto)
    REFERENCES TIPOIMPUESTO(IdImpuesto);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_FICHAJE_USUARIOS')
BEGIN
    ALTER TABLE FICHAJE
    ADD CONSTRAINT FK_FICHAJE_USUARIOS
    FOREIGN KEY (IdUsuario)
    REFERENCES USUARIOS(IdUsuario);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_FICHAJE_TIPO')
BEGIN
    ALTER TABLE FICHAJE
    ADD CONSTRAINT FK_FICHAJE_TIPO
    FOREIGN KEY (IdTipo)
    REFERENCES TIPOFICHAJE(IdTipo);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_NOMINAS_USUARIOS')
BEGIN
    ALTER TABLE NOMINAS
    ADD CONSTRAINT FK_NOMINAS_USUARIOS
    FOREIGN KEY (IdUsuario)
    REFERENCES USUARIOS(IdUsuario);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HISTORICO_TIPO')
BEGIN
    ALTER TABLE HISTORICO
    ADD CONSTRAINT FK_HISTORICO_TIPO
    FOREIGN KEY (IdTipoObjeto)
    REFERENCES OBJETOTIPO(IdTipo);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_LOGS_USUARIOS')
BEGIN
    ALTER TABLE LOGS
    ADD CONSTRAINT FK_LOGS_USUARIOS
    FOREIGN KEY (IdUsuario)
    REFERENCES USUARIOS(IdUsuario);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_CALIFICACIONES_USUARIOS')
BEGIN
    ALTER TABLE CALIFICACIONES
    ADD CONSTRAINT FK_CALIFICACIONES_USUARIOS
    FOREIGN KEY (IdUsuario)
    REFERENCES USUARIOS(IdUsuario);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_CALIFICACIONES_PRODUCTOS')
BEGIN
    ALTER TABLE CALIFICACIONES
    ADD CONSTRAINT FK_CALIFICACIONES_PRODUCTOS
    FOREIGN KEY (IdProducto)
    REFERENCES PRODUCTOS(IdProducto);
END
GO


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_INVENTARIO_INGREDIENTES')
BEGIN
    ALTER TABLE INVENTARIO
    ADD CONSTRAINT FK_INVENTARIO_INGREDIENTES
    FOREIGN KEY (IdIngrediente)
    REFERENCES INGREDIENTES(IdIngrediente);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_INVENTARIO_RESTAURANTES')
BEGIN
    ALTER TABLE INVENTARIO
    ADD CONSTRAINT FK_INVENTARIO_RESTAURANTES
    FOREIGN KEY (IdRestaurante)
    REFERENCES RESTAURANTES(IdRestaurante);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PROMOCION_TIPOPROMOCION')
BEGIN
    ALTER TABLE PROMOCIONES
    ADD CONSTRAINT FK_PROMOCION_TIPOPROMOCION
    FOREIGN KEY (IdTipo)
    REFERENCES TIPOPROMOCION(IdTipo);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PRODUCTO_PROMOCION')
BEGIN
    ALTER TABLE PRODUCTOS
    ADD CONSTRAINT FK_PRODUCTO_PROMOCION
    FOREIGN KEY (IdPromocion)
    REFERENCES PROMOCIONES(IdPromocion);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PRODUCTO_PROMOCION')
BEGIN
    ALTER TABLE PRODUCTOS
    ADD CONSTRAINT FK_PRODUCTO_PROMOCION
    FOREIGN KEY (IdPromocion)
    REFERENCES PROMOCIONES(IdPromocion);
END
GO